spring.application.name=task-management
server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskmanagement}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:task_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:task_pass}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
